= Philips Hue Library for ESP8266 =

This library is designed to access and control Philips Hue Lights Directly with an ESP8266 using the Arduino IDE.

To use:

  1. Download ZIP
  
  2. In Arduino IDE from the menu Sketch->Include Library->Add .ZIP Library...
  
  3. Browse to the .zip file and install
  
  4. Library will show up under Include Library
  
  5. Examples are in File->Examples->ESP_Hue
  
Available Class Methods:

	void setAPIKey(const char* APIKey);
		
	void setHubIP(const char* host);
		
	void setHubPort(uint8_t port);
		
	String getLightInfo(int lightNum);  								// Gets the light raw http request data
	
	int getLightState(int lightNum);									// Gets Light State On, or Off
	
	void setLight(int lightNum, int state, int sat, int bri, int hue);  // Set Light State, Saturation, Brightness, and Hue
	
	void setLight(int lightNum, int state, int sat, int bri, int hue, unsigned int trans);  // Set Light State, Saturation, Brightness, and Hue, with transition speed
	
	void setLightTemperature(int lightNum, int state, int bri, unsigned int ct);  // Set Light State, Brightness, and Light Temperature
	
	void setLightTemperature(int lightNum, int state, int bri, unsigned int ct, unsigned int trans);  // Set Light State, Brightness, and Light Temperature, with transition speed
	
	void setLightPower(int lightNum, int state);						// Set Light Power On, or Off

	String getGroupInfo(int groupNum);									// Gets the group raw http request data

	int getGroupState(int groupNum);									// Gets Group State On, or Off

	void setGroup(int groupNum, int state, int sat, int bri, int hue);  // Set Group State, Saturation, Brightness, and Hue
	
	void setGroup(int groupNum, int state, int sat, int bri, int hue, unsigned int trans);  // Set Group State, Saturation, Brightness, and Hue, with transition speed

	void setGroupTemperature(int groupNum, int state, int bri, unsigned int ct);  // Set Group State, Brightness, and Light Temperature
	
	void setGroupTemperature(int groupNum, int state, int bri, unsigned int ct, unsigned int trans);  // Set Group State, Brightness, and Light Temperature, with transition speed

	void setGroupPower(int groupNum, int state);	                 	// Set Group Power On, or Off

See Examples for Usage


------------------------------------------------------------------------------------
== License ==

Copyright (c) Richard Wardlow. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
